### PR TITLE
fix: correct reference length calculation

### PR DESCRIPTION
**Pull request by yuxqiu**
### Summary

This PR fixes the way brevity penalty (specifically the effective reference corpus length) is calculated in BLEU.

Previously, `len_reference` was calculated as `min([len(ref) for ref in references_tokenized])`. However, this is incorrect, because according to the paper, we need to find the "best match length", not the minimum reference length.

For more information, see [wikipedia - brevity penalty](https://en.wikipedia.org/wiki/BLEU#Brevity_penalty) and [nltk implementation](https://www.nltk.org/_modules/nltk/translate/bleu_score.html#closest_ref_length).

### Test plan

I added another unit test to `test_bleu.py` and compared the results of the calculations to the results of the `nltk.translate.bleu_score.corpus_bleu` function to make sure the implementation is correct.

### CODE REVIEW

**Comment by yuxqiu** [comment]
Hi, I am wondering if there is a way for me to get the reason why the test is failing so that I can fix the problem.

**Comment by JKSenthil** [comment]
Hi @yuxqiu, thanks for this contribution! it seems some files unrelated to BLEU have been formatted in a way in which causes our linter to error, do you mind undo-ing those changes?

**Comment by yuxqiu** [comment]
@JKSenthil I've finished undo-ing all those changes.

**Comment by JKSenthil** [comment]
Hi @yuxqiu, thanks for reverting! We have identified the linter issue to be on our end, we'll land a fix first then rerun these tests again :)

**Pull request closed without merging**
