### PR TITLE
Pyre Configurationless migration for] [batch:82/112] [shard:6/N]

### PR DESCRIPTION
**Pull request by connernilsen**
Summary:
X-link: https://github.com/facebook/sapp/pull/108

X-link: https://github.com/pytorch/torchsnapshot/pull/168

X-link: https://github.com/pytorch/tnt/pull/717

X-link: https://github.com/facebook/pyre-check/pull/818

Reviewed By: connernilsen

Differential Revision: D54436435

### CODE REVIEW

**Comment by bobakfb** [comment]
Seems like this was a mistake?

**Comment by connernilsen** [comment]
Hey @bobakfb, this wasn't a mistake. For updates coming to Pyre, we need to apply these comments in Python files that you want type checked.

It's not urgent that this is done, but starting in a few weeks, some functionality will stop working for type checking in the IDE. In around 6 months, type checking will stop working completely on these files. You can read more about this migration [here](https://fb.workplace.com/groups/295311271085134/permalink/1418785355404381/).

If you don't want this migration to happen for torcheval, I can block the migration from going through for now. Just let me know here and I can make that change.

**Comment by connernilsen** [comment]
I'm going to retry again later.

**Comment by bobakfb** [comment]
Hey conner, I think it's fine to push this, but the linked diff on phabricator doesn't have the code linked in this PR. One thing to note is that we do ignore one particular warning at the top of all our class-based metrics, not sure if there is anything to consider there.

**Pull request closed without merging**
